server:
  error:
    include-message: always
  port: 8080
  servlet:
    context-path: /web-market-cart
utils:
  cart:
    prefix: SPRING_WEB_
integrations:
  core-service:
    url: http://localhost:8189/web-market-core
  rec-service:
    url: http://localhost:8155/web-market-rec

